// Client-side export helpers for IntelBot answers. Called only from event
// handlers in the browser, so DOM/Blob/window usage is safe here.

function slug(s: string): string {
  return (s || "intelbot-answer")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 48);
}

function triggerDownload(filename: string, content: string, mime: string): void {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function downloadMarkdown(content: string, title: string): void {
  triggerDownload(`${slug(title)}.md`, content, "text/markdown;charset=utf-8");
}

// Extract every GFM table from the markdown and emit CSV (tables separated by a
// blank line). Returns null if the answer contains no tables.
export function markdownTablesToCsv(md: string): string | null {
  const lines = md.split(/\r?\n/);
  const isRow = (l: string) => /^\s*\|.*\|\s*$/.test(l);
  const isSep = (l: string) => /^\s*\|?[\s:-]*\|[\s:|-]*$/.test(l) && l.includes("-");

  const cells = (l: string) =>
    l
      .trim()
      .replace(/^\||\|$/g, "")
      .split("|")
      .map((c) => c.trim());

  const csvCell = (c: string) =>
    /[",\n]/.test(c) ? `"${c.replace(/"/g, '""')}"` : c;

  const tables: string[] = [];
  let i = 0;
  while (i < lines.length) {
    if (isRow(lines[i]) && i + 1 < lines.length && isSep(lines[i + 1])) {
      const out: string[] = [cells(lines[i]).map(csvCell).join(",")];
      i += 2; // skip header + separator
      while (i < lines.length && isRow(lines[i])) {
        out.push(cells(lines[i]).map(csvCell).join(","));
        i++;
      }
      tables.push(out.join("\n"));
    } else {
      i++;
    }
  }
  return tables.length ? tables.join("\n\n") : null;
}

export function downloadCsv(md: string, title: string): boolean {
  const csv = markdownTablesToCsv(md);
  if (!csv) return false;
  triggerDownload(`${slug(title)}.csv`, csv, "text/csv;charset=utf-8");
  return true;
}

const PRINT_CSS = `
  * { box-sizing: border-box; }
  body { font: 14px/1.6 -apple-system, Segoe UI, Roboto, Arial, sans-serif; color: #111; max-width: 800px; margin: 32px auto; padding: 0 24px; }
  h1.doc-title { font-size: 20px; margin: 0 0 4px; }
  .meta { color: #666; font-size: 12px; margin-bottom: 20px; border-bottom: 1px solid #ddd; padding-bottom: 12px; }
  h1, h2, h3 { line-height: 1.3; }
  table { border-collapse: collapse; width: 100%; margin: 12px 0; font-size: 13px; }
  th, td { border: 1px solid #bbb; padding: 6px 9px; text-align: left; vertical-align: top; }
  th { background: #f3f4f6; }
  code { background: #f3f4f6; padding: 1px 4px; border-radius: 3px; font-size: 12px; }
  pre { background: #f3f4f6; padding: 10px; border-radius: 6px; overflow-x: auto; }
  blockquote { border-left: 3px solid #ccc; margin: 12px 0; padding: 2px 12px; color: #444; }
  a { color: #1a5fb4; }
  .foot { margin-top: 28px; padding-top: 12px; border-top: 1px solid #ddd; color: #888; font-size: 11px; }
  @media print { body { margin: 0; } }
`;

// Open a print-ready window from the already-rendered answer HTML; the user
// chooses "Save as PDF". Produces a clean, selectable-text document.
export function printAnswer(innerHtml: string, title: string, question?: string): void {
  const w = window.open("", "_blank", "width=860,height=900");
  if (!w) return;
  const esc = (s: string) =>
    s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  w.document.write(
    `<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title>` +
      `<style>${PRINT_CSS}</style></head><body>` +
      `<h1 class="doc-title">IntelBot — Noonan</h1>` +
      `<div class="meta">${question ? esc(question) + " · " : ""}${new Date().toLocaleString()}</div>` +
      `<div class="content">${innerHtml}</div>` +
      `<div class="foot">Generated by IntelBot · grounded in Noonan's knowledge base · general guidance, not legal advice.</div>` +
      `</body></html>`
  );
  w.document.close();
  w.focus();
  setTimeout(() => w.print(), 350);
}
